### ISSUE TITLE
Email active border-bottom

### ISSUE THREAD

**Issue by comerc** [ianmartorell/meteor-accounts-ui-bootstrap-3#42]
![border](https://cloud.githubusercontent.com/assets/1025241/5719720/03d56b5e-9b2c-11e4-8366-16bd4c5c10e5.png)

**Comment by comerc** [comment]
may be `z-index`

**Comment by ianmartorell** [comment]
I'm trying to find a solution to this, but it looks like z-index won't do it

**Comment by comerc** [comment]
You may use this solution:
```css
input#login-email, input#login-password, input#login-old-password, input#login-password { position: relative; z-index: 1; }
input#login-email:focus, input#login-old-password:focus { z-index: 2; }
```
