### ISSUE TITLE
Missing icon in OAuth services

### ISSUE THREAD

**Issue by Francescu** [ianmartorell/meteor-accounts-ui-bootstrap-3#49]
When adding a third party OAuth service, it usually add an icon into its CSS this way (using `steam` as service name example):
```css
#login-buttons-image-steam {
  background-image: url(data:image/png;base64,XXXX=);
}
```

Then the regular accounts-ui add this `div` on the left inside the "button":
```html
<div class="login-image" id="login-buttons-image-steam"></div>
```
