### ISSUE TITLE
Opacity 

### ISSUE THREAD

**Issue by comerc** [ianmartorell/meteor-accounts-ui-bootstrap-3#51]
For: https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/accounts_ui.styl#L36
See here: http://getbootstrap.com/css/#less-mixins-vendor
Set the opacity for all browsers and provide a filter fallback for IE8.
```less
.opacity(@opacity) {
  opacity: @opacity;
  // IE8 filter
  @opacity-ie: (@opacity * 100);
  filter: ~"alpha(opacity=@{opacity-ie})";
}
```
