### ISSUE TITLE
Is it possible to have it without the dropdown just a simple sign up box? 

### ISSUE THREAD

**Issue by almogdesign** [ianmartorell/meteor-accounts-ui-bootstrap-3#74]
Is it possible to have it without the dropdown just a simple sign up box?

**Comment by ianmartorell** [comment]
Sorry, no. You'd have to design that sign up box, so you're better off extending the `accounts-base` package yourself, or forking this package and modifying it yourself. If you do that you can submit a pull request later on.

**Comment by lucatros** [comment]
In case you find it useful, I managed to get rid of the dropdown with some jQuery and CSS.

HTML: 

 ````html
<div id="login-box">{{> loginButtons}}</div>
````

Remove the toggle and show the dropdown menu:
````javascript
Template.login.rendered = function () {
	 $('.dropdown-toggle').remove();
	 $('.dropdown-menu').show();
}
````

And the CSS:

````css
#login-box li.dropdown {
  list-style-type: none;
  padding: 0px;
  margin: 0px;
}

#login-box li.dropdown .dropdown-menu {
  float: none;
  position: relative;
  background-color: #ffffff;
}

#login-box li.dropdown .dropdown-menu .alert-danger {
  color: #a94442;
}

#login-box li.dropdown .dropdown-menu:after  {
visibility: hidden;
  display: block;
  font-size: 0;
  content: " ";
  clear: both;
  height: 0;
}
````

There are some extra CSS properties that are just for my personal taste, but you'll get the idea.
